### ISSUE TITLE
StorageMemoryCache - a synchronous, on-demand sparse cache

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#110]
### Motivation

Some of our Storages are async and slow, such as IndexedDb (when it's done) or maybe a proxy'd connection to a remote peer.

But it's very convenient for React to have a fast synchronous storage.  This helps with
1. Rendering is easier if reading is synchronous
2. Writing works better if we can optimistically keep around the new version until we've confirmed it's written to the underlying slow storage, so we can render it without waiting

Also, this could be placed in front of a remote peer, like this, in case we didn't want to store any data locally:
`[local peer: StorageMemoryCache] <--network--> [remote peer: StorageSqlite]`

### Idea

We could make a new Storage type, StorageMemoryCache, which holds only recently accessed documents.  It syncs with other storages using the regular sync mechanisms.

This new Storage could be "sparse" in one of two ways:
* ["sparse mode"](https://github.com/earthstar-project/earthstar/issues/33) holding metadata for all documents but not necessarily the content, fetching and dropping the content depending on circumstances
* ["selective sync"](https://github.com/earthstar-project/earthstar/issues/6) - only holding some documents and not others

**Comment by sgwilym** [comment]
I made a POC of this storage, though it works differently than described above: https://github.com/earthstar-project/react-earthstar/blob/v3/src/StorageMemoryCache.ts

- This storage remembers all the queries made to it, and caches their results. 
- On a cache miss, it requests the documents from the backing storage, saves it in the cache, and informs subscribers via the `onWrite` emitter.
- On a cache hit, it serves up what's in the cache. It checks if the result has expired, and if so, requests the documents from the backing storage again.
- On a local operation like `set`, it upserts the document into the cache, creating a cache entry for the query for just the document if it's not already there, and updating the document in any cache entries it finds itself in.
- The cache is also subscribing to write events from the backing storage, and upserts documents from those events in the same way as described above.

And that shakes out like this:

**Getting**
1. On the first request for documents, nothing is returned.
2. On the second request for documents, the expected result is returned.

**Setting**
1. On a document `set`, that document will be available in any subsequent request.

Having this means that react-earthstar can effectively support any kind of storage, synchronous or not, and simplify its internals by not having to deal with asynchronous code (not hypothetical - the v3 branch does this!) It's not every day you get to make your package simpler and more versatile, but this is one of those times!

So I'm really motivated to bring a polished version of _something with the same effect_ into earthstar-core. I made this request cache variant of the idea above because it had fewer dependencies like sparse mode and selective sync. It already mostly works, but I'm interested in figuring out the best way to get it into core.

- It's been written as a class inheriting from StorageBase. Maybe it'd be better as a proxy? In my v3 branch I'm using it in combination with @cinnamon-bun's `StorageProxy` experiment from a while back. Can you have a proxy of a proxy, or would it be better to combine their features together into a single proxy? Though wouldn't a proxy of an async storage force the async API on the proxy...?
- It can't correctly determine the `isLatest` property of a doc's write event, due to not having access to the whole set of documents to compare to. I understand this is something @cinnamon-bun has bumped against too.
- This is my first time writing any kind of cache implementation. It wouldn't surprise me if there were better ways to implement the same thing!
  - For example, the map of cached requests uses the object identity of the query to match keys. I did this because it seemed faster that de/serialising all the queries all the time. Maybe that's not such a big deal?
