### ISSUE TITLE
Make tests run in browsers

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#2]
Get tooling in place to run all the tests in a browser environment.

**Comment by sgwilym** [comment]
I did a little bit of looking into this as earthstar-graphql also needs tests that run in a node-like environment and a browser-like one. In that repo I'm using jest, which lets you configure the [environment used for testing](https://jestjs.io/docs/en/configuration#testenvironment-string): you can use `jsdom` to test how code would run in a browser. I'm going to try configuring it so that the same test suites run in both environments.

But that's not very useful here, is it? 😅 It seems like tap is made specifically for testing in node environments? I couldn't find docs about configuring it otherwise.

I will see how this shakes out in earthstar-graphql, and if there is ever any appetite to migrate tests to jest in this repo, I'm more than happy to help.

**Comment by cinnamon-bun** [comment]
Yeah, turns out `tap` only works in node.  But `tape` is almost identical and it can be browserified!  So I kinda got this working but it's awkward.

(`jsdom` doesn't help here since it just emulates browser APIs and we need to test the actual browser javascript engine.)

Commit: https://github.com/earthstar-project/earthstar/commit/8a2bd98fa110b345cd1c5dda7ab3520e34ff796d

Docs are in `karma.conf.js`, also pasted below.

Unfortunately this didn't detect #48 "detChoice problems in browser", it just worked.  :/  In headless chrome, anyway.

---

### How this works

Run `npm run test-in-browser` to do all these steps at once:
1. npm run clean
2. npm run build    // typescript build
3. npm run browserify-for-karma   // make a bundle from one test file
4. npm run karma    // run karma headless browser test on the bundle

The browserify step currently can only process one of the *.test.js files.
It's hardcoded in package.json in the "browserify-for-karma" step.
Change it there to run different tests.
To fix this, I think browserify would need to make a separate bundle
for each of our *.test.js files.

### ALSO

The `tap` module is not browserifiable.  We tell browserify to
swap it for `tape` (see the `browser` section of package.json).
tape's API is almost identical except it doesn't have t.done(), it has t.end().
So write all the tests using t.end(), which works in both.

### FUTURE IMPROVEMENTS

The npm packages `karma-browserify` and `karma-typescript` look promising
but I was not able to get them working.
