### ISSUE TITLE
Earthstar on browser doesn't load documents correctly

### ISSUE THREAD

**Issue by Vicente015** [earthstar-project/earthstar#357]
Using the latest Earthstar version on browser with IndexedDB

## What's the problem you want solved?
I have a page that on load initiates everything needed to use Earthstar (peer, identity, share, store) with the credentials stored in the local store, then loads the existing documents from the store (`store.documents`).

When accessing the page, Earthstar does not return any document, when a new document is created then I call `store.documents` again but it only returns the ones created since this initialisation, not the previous ones.

## Reproduction steps
I have made a project to reproduce it just using Vite and TypeScript in only 90 lines of code.

Steps:
1. Clone [repo](https://github.com/Vicente015/earthstar-bug-repro/), `git clone https://github.com/Vicente015/earthstar-bug-repro.git && cd earthstar-bug-repro/`
2. Install dependencies: `npm install`
3. Run Vite: `npm run dev`
4. Open the website on your browser
5. Look at the console and localStorage in DevTools to see how Earthstar is being initialized
6. Click "Create new document" button, see on console how it loads this document
7. Reload the page
8. See on console how it doesn't load any document

All the code is on `src/repro.ts`

**Comment by sgwilym** [comment]
Hi! Thank you for this report. It led to me finding several issues with in this repo and willow-js (detailed below).

Please check if [v11.0.0-beta.7](https://jsr.io/@earthstar/earthstar@11.0.0-beta.7) fixes this issue for you. After installing, please verify that the version of willow-js is 0.6.**1**.

I will now explain the problems, in order of descending stupidity:

- Earthstar's IndexedDB driver didn't use Willow's IndexedDB driver, but its in-memory driver. This is why data was not being persisted between refreshes.
- Willow's IndexedDB KV driver was not namespaced, so data from all kinds of different places (auth, other namespaces) would all end up in the same database.

(at this point I could find the _real_ IndexedDB bugs) 

- Calls to `KvBatch.commit` were not being properly bound when put into a `PrefixedKvDriver`.
- Attempts to list through entries on Safari would break due to using `nextunique` / `prevunique` on a non-index query.
- Invalid `IDBBound`s could be created when attempting to summarise certain ranges.

**Comment by Vicente015** [comment]
I can confirm that the issue has been fixed, thanks a lot!
