### ISSUE TITLE
Add helper functions for deterministic random colors by author address

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar#41]
## What's the problem you want solved?

In a user interface, two authors could look identical if we only show their shortnames and display names and not their pubkeys.

## Is there a solution you'd like to recommend?

Give each author a random color that's deterministically derived from their author address.

The function should also accept a `salt` parameter which could be made different on each device.  That way an imposter won't be able to generate a pubkey with a similar looking color because they won't know your salt.

Here's a way I did this in the past.  It will need to be adapted to base32.
```ts
export let detRandom = (s : string) : number => {
    // return random-ish float between 0 and 1, deterministically derived from a hash of the string
    let m = md5(s) as string;
    return parseInt(m.slice(0, 16), 16) / parseInt('ffffffffffffffff', 16);
};
```

**Comment by sgwilym** [comment]
I was thinking about how people affected by colour blindness would not be able to benefit from this feature. Are there other ways we could create a more recognisable fingerprint? One that could scale to visually-impaired users, even?

Like a mnemonic phrase, which could be read visually or spoken, e.g.

`balcony lemon haunted walnut`

**Comment by cinnamon-bun** [comment]
> mnemonic phrase

Manyverse uses this for key recovery.  (It takes 24 words to fully specify a pubkey.)  This is a bit hard to internationalize though, you have to find a wordlist for each language which won't accidentally make offensive combinations.

https://www.npmjs.com/package/ssb-keys-mnemonic

I like the random emoji approach used by Riot.im / Element.io.  We would need to standardize on an emoji font so it matches across platforms.

![DzYg1ZTWoAEFvDl](https://user-images.githubusercontent.com/32660718/90302308-180ab800-de5a-11ea-9cbd-bab6daa0fdd5.png)

---

> colour blindness 

Yes, thanks for raising that issue.  We can have lots of different signals all added together:

* Random colors, maybe 2 or 3 colors per author in a little flag or something
* Random avatars like [identicon](http://identicon.net/)
* Random left padding?  I've always wanted this for crowded chatrooms, it makes it much easier to follow conversations:

![Screen Shot 2020-08-14 at 6 10 39 PM](https://user-images.githubusercontent.com/32660718/90302220-813dfb80-de59-11ea-8cf8-0e8eefc45820.png)

**Comment by sgwilym** [comment]
Re: wordlists, understood!

Emoji key is cool. How do you imagine that being used? As a label following a shortname?

In lobby, my desire is to have some identifier that is always visible, so that you don’t need to expand any UI to mostly verify an identity. For this reason, I would also like the identifier to be compact so that it can be presented inline with a shortname without needing too much space.

Re: mayn signals. Different signals added together I find a bit overwhelming, and have an unproven hunch that it’d make it easier to miss that one of the signals was awry.

I’m surprised at how well the random indentation for a chat format works. I wonder how well it scales with multiline messages, though.

My absolute favourite is identicons. I think a small identicon… 5x5, in black and white (or white on black), inline with a short name could look great. It’s also easy to try out, so I’m going to try it in the lobby and we can see how we feel about it!

**Comment by sgwilym** [comment]
I've added mini-identicons to earthstar-lobby:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/579491/90392278-dca4ff00-e08e-11ea-8852-c0d6c4951b71.png">

What do you think?

**Comment by cinnamon-bun** [comment]
I think identicons are sufficient, yeah!

I'll repost here what I already said in the lobby, just for history's sake:

> Re identicons, it's even more secure if they're derived from the author's address + your own secret, so they look different to every user. It makes it harder to generate a fake identity with a matching identicon. (But it also means you can't compare identicons with other users, since they look different to everyone)

And I personally find that random indentation helps me follow conversations, even aside from its security purposes.  I don't know if it would work on a narrow phone screen though.

**Comment by cinnamon-bun** [comment]
I added `detRandom` and similar helper functions in [5.2.1](https://github.com/earthstar-project/earthstar/releases/tag/v5.2.1).

Closing this as a TODO item, but feel free to continue the conversation here.
